### ISSUE TITLE
Improve Structure of NemoTimeMeanTemporalMap

### ISSUE THREAD

**Issue by valentinaschueller** [valentinaschueller/scriptengine-tasks-ecearth#106]
See [this file](https://github.com/valentinaschueller/scriptengine-tasks-ecearth/blob/master/scriptengine/tasks/ecearth/monitoring/nemo_time_mean_temporalmap.py).

How should the `__init__` function of NemoTimeMeanTemporalMap, NemoMonthMeanTemporalMap, and NemoYearMeanTemporalMap look like?

The parameters `varname`, `src`, `dst` should be required for instantiating the child classes because NemoTimeMeanTemporalMap requires these for its `run()` function. On the other hand, the derived classes of NemoTimeMeanTemporalMap might require additional input parameters in the future (e.g. `season` for a possible NemoSeasonMeanTemporalMap implementation).

What is a good structure for this?

**Comment by uwefladrich** [comment]
One way out would be like this:
```python
class Map(Task):
  def __init__(self, param):
    super().__init__(param, required=['arg1', 'arg2'])

class SomeMap(Map):
  def __init(self, param):
    Task.__init__(self, param, required=['arg1', 'arg2', 'arg3'])
```
This would do the required setup, I think. However, there are two slight disadvantages:

- The definition of `__init__` looks a bit "unsymmetric" between `Map` and `SomeMap`. Of course one could use the same call for `Map` as for `SomeMap`, not taking advantage of the `super()` call.
- It is not really hierarchical, i.e. the required arguments of `Map` are not automatically required for `SomeMap`. On the other hand, it could be seen as additional flexibility.

**EDIT:** Add missing parantheses in code example.

**Comment by uwefladrich** [comment]
Another option that follows the inheritance hierarchy better is:
```python
class Map(Task):
  def __init__(self, param, required=None):
    super().__init__(param, required=['arg1', 'arg2']+(required or []))

class SomeMap(Map):
  def __init__(self, param):
    super().__init__(param, required=['arg3'])
```
