### ISSUE TITLE
f-string not necessary in presentation_objects code?

### ISSUE THREAD

**Issue by uwefladrich** [valentinaschueller/scriptengine-tasks-ecearth#129]
Small thing:

https://github.com/valentinaschueller/scriptengine-tasks-ecearth/blob/da827ee53b6ecec6ea92a6e49b140292ba65e451/helpers/presentation_objects.py#L158

is the f-string really necessary in this line? Couldn't it just be
```python
unit_text = format_units(self.cube.units)}
```

**Comment by uwefladrich** [comment]
Sorry, I realise I opened this issue in the wrong repo. @valentinaschueller , we should do this in [uwefladrich/scriptengine-tasks-eceart ](https://github.com/uwefladrich/scriptengine-tasks-ecearth), shouldn't we?

**Comment by valentinaschueller** [comment]
yes!

**Comment by uwefladrich** [comment]
Okay, closing here and opening there ;-)
