### ISSUE TITLE
Rename Processing Tasks for Consistency

### ISSUE THREAD

**Issue by valentinaschueller** [valentinaschueller/scriptengine-tasks-ecearth#44]
e.g. GlobalAverage --> OceanGlobalAverage? OrcaGlobalAverage? OrcaGlobalAverage?

**Comment by valentinaschueller** [comment]
Possible Parameters to name modules:
- diagnostic type (scalar, time series, static map, dynamic map)
- global/hemispheric
- spatial/temporal average/min/max
- treated variable
- orca/reduced gaussian grid
- atmosphere/ocean/sea ice/computational performance

## Module Name Suggestions

### Scalars

- `scalar_custom_input`
- `scalar_disk_usage`
- `scalar_simulated_years`
- `scalar_simulated_legs`

### Time Series

- `time_series_orca_global_average`
- `time_series_orca_sivol`
- `time_series_orca_siarea`
- `time_series_redgg_global_average`
- `time_series_sypd`

### Static Maps

- `static_map_orca_average`
- `static_map_redgg_average`
- `static_map_orca_sivol`

### Dynamic Maps

- `dynamic_map_orca`
- `dynamic_map_redgg`
- `dynamic_map_orca_siconc`

## Presentation

- `presentation_jinja_template`
- `presentation_redmine_upload`
- `presentation_compress_output`
- ...?

**Comment by uwefladrich** [comment]
As mentioned in #2 (and related to #3), this is a more general discussion about naming things.

I would like to generalise your list from above slightly:

* **realm**
  atmosphere, ocean, sea-ice, land, computational performance
* **domain**
  global, northern/southern hemisphere
* **diagnostic type**
  scalar, time series, static map, dynamic map
* **operation**
  spatial/temporal average/min/max
* **grid**
  ORCA1, TL255 (reduced gaussian grid)
* **variable**

I tried to use the CMIP6 CV where it makes sense and I also tried to put things in an order that is somewhat hierarchical. Not sure I succeeded, but maybe its a beginning of a naming scheme.
