### ISSUE TITLE
Processing Tasks for 3D variables, AMOC, regional phenomena?

### ISSUE THREAD

**Issue by valentinaschueller** [valentinaschueller/scriptengine-tasks-ecearth#90]
So far, the processing tasks are only dealing with global 2D variables from the NEMO/OpenIFS output. Maybe add a processing task for 3D variables? Or one that computes the AMOC or other regional phenomena?

**Comment by uwefladrich** [comment]
I'm quiet sure that this will eventually be a topic. However, my feeling is that for now we need a phase with consolidation. The concept needs more review (we have some *concept* issues already), the code some cleaning here and there, and generally the monitoring needs more usage and testing in practical settings. I'm afraid that if we add too many features too fast, we will just mess up the code (see [this video snippet](https://www.youtube.com/embed/7EmboKQH8lM?start=1468&end=1932) for what I mean :wink:)
By that, I do not mean that a 3d task is far away, I think we could address this in a few weeks.

**Comment by valentinaschueller** [comment]
Something to keep in mind when this discussion starts up again: The tasks `nemo_global_mean_year_mean_timeseries` and `oifs_global_mean_year_mean_timeseries` should be able to deal both with 2D and 3D variables. (Otherwise, 2D and 3D task would have the same name according to the scheme)

**Comment by valentinaschueller** [comment]
Here are some relevant **ocean** diagnostics we cannot treat so far:

* a global map of the Barotropic stream function (depth-integrated volume transport). If XIOS can write out this variable directly, this can be treated directly. If not, we need a processing task á la `nemo_depth_integral_all_mean_map` or simlar. Regional maps of this variable will require (a processing task? and) a map type handling function that can deal with regional plots.
* AMOC: We are interested in the time series of the maximum of a variable in a lat-depth region, to create an AMOC index time series. A map of this lat-depth region can also be interesting
* mixed layer depth: an interesting diagnostic would be a Labrador sea mean of the mixed layer depth.

ENSO diagnostics are less relevant for monitoring and more relevant for analysis. The ENSO is typically visualized using a frequency plot which does not fit into our current diagnostic types.

**EDIT**
Comment from David regarding AMOC: time series for "maximum AMOC at 26N (using the Atlantic meridional stream function diagnostic, called zomsfatl in the outputs) "

**Comment by valentinaschueller** [comment]
**Atmosphere Diagnostics**

From David: It is probably useful to have a map of sea-level pressure here (variable 151 in IFS). Other useful diagnostics include the 10m wind speed (variables 165 and 166) and all the radiation fluxes (surface net solar [176] and thermal [177], top net solar [178] and thermal [179], surface sensible [146] and latent [147] heat flux).

From the EC-Earth 3 Post-Processing Tool I found these relevant time series diagnostics which we can not treat yet:
- precipitation minus evaporation: `tp+e`, mm/day
- top of atmosphere net heat flux: `tsr+ttr`, Wm-2
- surface net heat flux with snowfall: `sshf+slhf+ssr+str+sfhf`, Wm-2
- surface net heat flux: `sshf+slhf+ssr+str`, Wm-2
Maybe all of these can be treated by an OpenIFS proc task that can sum up different variables.

We should also try to figure out how we can deal with data that accumulates over time (e.g. tp, e)
